version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: . ./prov_vagrant/circleci.sh
      - run: ./scripts/new-kali.sh
      - run: ls
      - run: cat variables.json

