version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: bash ./scripts/new-kali.sh
      - run: bash ./ci/packer_build.sh
      - store_artifacts:
          path: /tmp/artifacts
