version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: . ./prov_vagrant/circleci.sh
      - run: ./prov_vagrant/new-kali.sh
      - run: ls
      - run: cat variables.json

